language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;' -u root
env:
  - username=travis
services:
  - mysql
notifications:
 slack: melmon201905fsf3:Yij5VzU6bwMExz2FfG7Iu6K5